// uni-preset-vue-vite/src/pages/post/postContent/postInput.vue
<script setup>
import { computed } from "vue";
import { ref, watch } from "vue"
const inputData = ref(null)
const post = defineProps(['id', 'commentid'])
console.log(
    post.commentid
)
/* const commentid = ref(null)
watch(post, () => {
    commentid.value = post.commentid
}) */
const emit = defineEmits(['reloadHandler'])
const localStorageData = JSON.parse(uni.getStorageSync('logindata'))
const sendInputData = () => {
    commentid.value[0] ? uni.request({
        url: `http://127.0.0.1:4000/addreply`,
        method: 'POST',
        header: {
            'content-type': 'application/json',// 设置请求头
            'Authorization': `Bearer ${localStorageData?.jwt}`, // 设置jwt
        },
        data: {
            data: {
                postId: post.id,
                commentId: post.commentid[0],
                replyUserId: localStorageData.userid,
                replyText: inputData.value,
                replyToreplyUserId: inputReplyData.replyToreplyUserId || null,
                replyImages: null,
                replyLike: 0,
                replyComment: null
            }
        },
        success: function () {
            emit('reloadHandler')
            inputData.value = ''
        },
        fail: function (res) {
            console.log(res)
        }
    }) :
        uni.request({
            url: `http://127.0.0.1:4000/addcomment/${post.id}`,
            method: 'POST',
            header: {
                'content-type': 'application/json',// 设置请求头
                'Authorization': `Bearer ${localStorageData?.jwt}`, // 设置jwt
            },
            data: {
                data: {
                    postId: post.id,
                    commentUserId: localStorageData.userid,
                    Text: inputData.value,
                    Image: null,
                    Like: 0
                }
            },
            success: function () {
                emit('reloadHandler')
                inputData.value = ''
            },
            fail: function (res) {
                console.log(res)
            }
        })
}

</script>
<template>
    <view class="input-box">
        <view>{{ post.commentid.username }}</view>
        <input class="input" placeholder="评论" v-model="inputData">
        <view class="input-button" @click="sendInputData">发表</view>
    </view>

</template>
<style>
.input-box {
    display: flex;
    flex-direction: row;
    justify-content: center;
    gap: 10rpx;
    width: 100%;
}

.input {
    background-color: #f6f6f6;
    height: 70rpx;
    border-radius: 10rpx;
    width: 70%;
}

.input-button {
    height: 70rpx;
    width: 15%;
    background-color: #f6f6f6;
    border-radius: 10rpx;
    display: flex;
    justify-content: center;
    align-items: center;
}
</style>

// React_towelClient/src/view/body/postComponents/postContent/PostInput.js

import React, { useState } from 'react'
import PostComment from './PostComment'
// import style from './PostInput.module.css'
import { useNavigate } from 'react-router'
import { getSocket } from '../../../../socket/socket'
import propTypes from 'prop-types'
import { postAddPostComment, postAddPostReply } from '../../../../services/post/post'
import useLocalStorage from '../../../../hooks/useLocaStorage'

export default function PostInput({ postId }) {
    const navigate = useNavigate()
    const [localStorageData] = useLocalStorage()
   

    const [inputData, setInputData] = useState('')//get the input value
    const [inputReplyData, setInputReplyData] = useState({}) //get thie input valur that who is @ value
    const [reLoad, seReLoad] = useState(false)//使相关了的get请求刷新
    function sendInputData() {
        postAddPostComment(postId, {
            data: {
                postId: postId,
                commentUserId: localStorageData.userid,
                Text: inputData,
                Image: null,
                Like: 0
            }
        }).then(() => {
            setInputData('')
            seReLoad(!reLoad)
        }).catch((error) => {
            console.log(error)
        })
    }
    const sendInputDataApi = () => {
        if ((localStorageData == {})) {
            navigate('/login')
        }
        else if (Object.keys(inputReplyData).length !== 0) {
            sendInputReplyDataApi()
        } else if (inputData !== '') {
            sendInputData()

        }
        else {
            console.log(' input to null')
        }
    }
    const sendInputReplyDataApi = () => {
        postAddPostReply({
            data: {
                postId: postId,
                commentId: inputReplyData.commentid,
                replyUserId: localStorageData.userid,
                replyText: inputData,
                replyToreplyUserId: inputReplyData.replyToreplyUserId || null,
                replyImages: null,
                replyLike: 0,
                replyComment: null
            }
        }).then(() => {
            const socket = getSocket()
            if (inputReplyData.replyToreplyUserId) {
                console.log(inputReplyData.replyToreplyUserId)
                //发送对方的id
                socket.emit(`newMessage`, { newMessage: true, userid: inputReplyData.replyToreplyUserId })
            }
            setInputData('')
            seReLoad(!reLoad)
        }).catch((error) => {
            console.log(error)
        })
    }
    return (
        <>
            <div className='flex flex-row justify-center h-8 mb-2 space-x-2 text-[--fontColor]'>
                {
                    Object.keys(inputReplyData).length !== 0 ?
                        <div className='flex items-center space-x-2'>
                            <div className='bg-[--boxColor] rounded-my-rounded-10px grow'>{inputReplyData.targetName}</div>
                            <div className=' w-6 h-6 rounded-full bg-[--boxColor] hover:bg-[--assistantColor] flex items-center justify-center' onClick={() => setInputReplyData('')}>X</div>
                        </div> : null
                }
                <input className='w-[15rem] bg-[--boxColor] rounded-my-rounded-10px focus:border-[--assistantColor]' value={inputData} onChange={(e) => setInputData(e.target.value)} placeholder='评论'></input>
                <button className='w-[4rem] h-8 rounded-my-rounded-10px bg-[--boxColor] hover:bg-[--assistantColor] hover:text-[--hostColor]' onClick={sendInputDataApi}>发表</button>
            </div>
            <PostComment reLoad={reLoad} postId={postId} setInputData={setInputReplyData}></PostComment>
        </>

    )
}
PostInput.propTypes = {
    postId: propTypes.string
}
