// Vue_towel/src/views/body/setting/Setting.vue
<script setup>
import { ref } from 'vue'
const menu = ref([
    { title: '明亮' ,url:'/setting/right'},
    { title: '暗黑' ,url:'/setting/drak'},
    { title: '跟随系统',url:'/setting/system' },
    { title: '忘记密码',url:'/setting/forgetpassword' },
    { title: '我的信息' ,url:'/setting/userinfo'},
    { title: '修改密码',url:'/setting/changepassword' },

])
</script>
<template>
    <main class="
    drfcd flex  rounded-lg  ">
        <div class="w-full flex  flex-col gap-2">
            <RouterLink v-for="(item, index) in menu " :key="index"
                :to="item.url"
                class=" h-12 bg-gray-500 rounded-lg flex justify-center items-center">
                {{ item.title }}
            </RouterLink>
        </div>
        <RouterView></RouterView>
    </main>
</template>
<style></style>

// app/setting/page.tsx
import { ModeToggle } from '@/components/ui/theme-button'
import Link from 'next/link'
import React from 'react'

export default function page() {
    const data = [
        {
            index: 1,
            title: '钱包',
            href: '/setting/wallet'
        },
      
        {
            index: 3,
            title: '修改密码',
            href: '/setting/changepassword'
        },
        {
            index: 4,
            title: '关于',
            href: '/setting/about'
        },
        {
            index: 5,
            title: '账号',
            href: '/setting/account'
        },

    ]
    return (
        <div className='flex flex-col gap-2'>
            {data.map((item) => <SettingLink key={item.index} href={item.href} title={item.title}></SettingLink>)}
            <ModeToggle></ModeToggle>
        </div>
    )
}
function SettingLink({ href, title }: { href: string, title: string }) {
    return (
        <Link href={href} className=' dark:hover:bg-[#353535] dark:bg-[#0a0a0a]  w-full flex flex-row justify-between items-center p-2 bg-gray-100 hover:bg-gray-200 rounded-xl'>
            <div>{title}</div>
            <div>&gt;</div>
        </Link>
    )
}
