// React_towelClient/src/view/foot/user/User.tsx
import React, { useState } from 'react'
import { Link } from 'react-router-dom'
import useLocaStorage from '../../../hooks/useLocaStorage'
import Premium from '../../../components/Premium'
export default function User() {
    const [localStorageData] = useLocaStorage()
    const [isShowPremium, setShowPremium] = useState(false)
    return (
        <div className='text-[--fontColor] w-full flex bg-[--boxColor] hover:bg-[--boxHoverColor] rounded-my-rounded-10px p-2 items-center space-x-2'>
            <div className='flex items-center  space-x-2'>
                <img src={localStorageData.headimg} className='w-10 h-10 rounded-full'></img>
                <Link className='font-bold' to={`/userhomepage/${localStorageData.userid}`}>{localStorageData.username}</Link>
            </div>
            <div className={`w-20 h-8  ${localStorageData.premium?'bg-[--assistantColor]':'bg-gray-300'} rounded-my-rounded-10px flex justify-center items-center cursor-pointer`} onClick={() => { setShowPremium(i => !i) }}>Premium</div>
            {isShowPremium && <Premium setShowPremium={setShowPremium}></Premium>}
        </div>
    )
}

// Vue_towelClient/src/views/body/user/user.vue
<script setup>
import { ref } from 'vue'
import Post from '../post/Post.vue'
import PostComment from '../post/postComment.vue'
import PostReply from '../post/postReply.vue'
import { useRoute } from 'vue-router';
import useLocaStorage from '../../../hook/useLocaStorage'
const title =ref(['帖子','评论','回复'])
const isShowWho=ref(0)
const router=useRoute()
const {getLocaStorageData,setLocaStorageData}=useLocaStorage()
const outLogin=()=>{
    setLocaStorageData()
    window.location.href='/'
}
</script>
<template>
    <main class="flex-1 flex flex-col  rounded-lg gap-6">
        <header class="flex justify-between items-center">
            <div class="flex items-center gap-2">
                <div class="h-12 w-12rounded-full ">
                    <img  class="h-12 w-12 rounded-full " :src='getLocaStorageData().headimg'/>
                </div>
                <span class="text-lg font-bold">{{getLocaStorageData().username}}</span>
            </div>
            <div class="flex items-center gap-2 ">
                <div class="font-bold text-lg text-red-500" @click="outLogin">登出</div>
                <div class="font-bold text-2xl">...</div>
            </div>
        </header>
        <div class="flex justify-around font-bold text-lg">
            <div v-for="(item,index) in title" :key="index" @click="isShowWho=index">{{item}}</div>
        </div>
        <Post  :userId='router.params.id' v-if="isShowWho===0"></Post>
        <PostComment :userId='router.params.id' v-if="isShowWho===1"></PostComment>
        <PostReply  :userId='router.params.id' v-if="isShowWho===2"></PostReply>
    </main>
</template>
<style></style>
