// React_towelClient/src/components/Image.tsx
import React from 'react'
import PropTypes from 'prop-types'
function Image(props) {
    const errorHandler = (e) => {
      e.target.src='https://raw.githubusercontent.com/GeKaixing/towel/refs/heads/main/README_static/logo.png'
    }
  return (
    <img src={props.src} onError={errorHandler} className={props.className} />  
  )
}

Image.propTypes = {
    src: PropTypes.string,
    className: PropTypes.string,
}

export default Image

// towel_for_Vue/src/components/Image.vue
<script setup lang="ts">
import { ref } from 'vue';

const props = defineProps({
  src: String,
  alt: String,

})
const emit = defineEmits(['click'])
const imgDom = ref()
const handleError=()=>{
  if(imgDom.value){
    imgDom.value?.setAttribute('src','https://raw.githubusercontent.com/GeKaixing/towel/main/README_static/logo.png')
  }
}
</script>
<template>
  <img ref="imgDom" class="object-scale-down " :src="props.src || 'https://raw.githubusercontent.com/GeKaixing/towel/main/README_static/logo.png'" @click="emit('click')" @error="handleError" :alt="props.alt"></img>
</template>
